# Railway Deployment Configuration
# This file tells Railway how to deploy your app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run dev"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = "3000"
